In [21]:
import pandas as pd

In [22]:
#preparing excel worksheet for import 
worksheet = 'fy23-fmr-zipcode.xlsx'
sheet_name = 'SAFMRs'

In [23]:
#reading overall df from excel sheet, this data can be used for counties all around the US if needed
fmr_df = pd.read_excel(worksheet, sheet_name=sheet_name)
fmr_df

,ZIP\nCode,HUD Area Code,HUD Metro Fair Market Rent Area Name,SAFMR\n0BR,SAFMR\n0BR - 90%\nPayment\nStandard,SAFMR\n0BR - 110%\nPayment\nStandard,SAFMR\n1BR,SAFMR\n1BR - 90%\nPayment\nStandard,SAFMR\n1BR - 110%\nPayment\nStandard,SAFMR\n2BR,SAFMR\n2BR - 90%\nPayment\nStandard,SAFMR\n2BR - 110%\nPayment\nStandard,SAFMR\n3BR,SAFMR\n3BR - 90%\nPayment\nStandard,SAFMR\n3BR - 110%\nPayment\nStandard,SAFMR\n4BR,SAFMR\n4BR - 90%\nPayment\nStandard,SAFMR\n4BR - 110%\nPayment\nStandard
0,76437,METRO10180M10180,"Abilene, TX MSA",620,558,682,660,594,726,860,774,946,1160,1044,1276,1440,1296,1584
1,76443,METRO10180M10180,"Abilene, TX MSA",620,558,682,660,594,726,860,774,946,1160,1044,1276,1440,1296,1584
2,76464,METRO10180M10180,"Abilene, TX MSA",620,558,682,660,594,726,860,774,946,1160,1044,1276,1440,1296,1584
3,76469,METRO10180M10180,"Abilene, TX MSA",620,558,682,660,594,726,860,774,946,1160,1044,1276,1440,1296,1584
4,79501,METRO10180M10180,"Abilene, TX MSA",660,594,726,700,630,770,900,810,990,1220,1098,1342,1480,1332,1628
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27326,85356,METRO49740M49740,"Yuma, AZ MSA",760,684,836,770,693,847,1010,909,1111,1430,1287,1573,1720,1548,1892
27327,85364,METRO49740M49740,"Yuma, AZ MSA",830,747,913,840,756,924,1100,990,1210,1550,1395,1705,1870,1683,2057
27328,85365,METRO49740M49740,"Yuma, AZ MSA",920,828,1012,930,837,1023,1220,1098,1342,1720,1548,1892,2080,1872,2288
27329,85366,METRO49740M49740,"Yuma, AZ MSA",810,729,891,810,729,891,1070,963,1177,1510,1359,1661,1820,1638,2002
27330,85367,METRO49740M49740,"Yuma, AZ MSA",1000,900,1100,1000,900,1100,1320,1188,1452,1860,1674,2046,2250,2025,2475

In [24]:
#creating new dataframe just for zip codes within Miami-Dade County 
miami_fmr_df = fmr_df[fmr_df['HUD Metro Fair Market Rent Area Name'] == 'Miami-Miami Beach-Kendall, FL HUD Metro FMR Area']

In [25]:
#dropping the 90% and 110% payment standard columns as they are not needed for this project
miami_fmr_df = miami_fmr_df.drop(columns=['HUD Metro Fair Market Rent Area Name', 'HUD Area Code','SAFMR\n0BR - 90%\nPayment\nStandard', 'SAFMR\n0BR - 110%\nPayment\nStandard','SAFMR\n1BR - 90%\nPayment\nStandard',
       'SAFMR\n1BR - 110%\nPayment\nStandard','SAFMR\n2BR - 90%\nPayment\nStandard',
       'SAFMR\n2BR - 110%\nPayment\nStandard','SAFMR\n3BR - 90%\nPayment\nStandard',
       'SAFMR\n3BR - 110%\nPayment\nStandard','SAFMR\n4BR - 90%\nPayment\nStandard',
       'SAFMR\n4BR - 110%\nPayment\nStandard'], axis=1)

In [26]:
#renaming columns for easier understanding
miami_fmr_df = miami_fmr_df.rename(columns= {'ZIP\nCode': 'zip_code', 
                                             'SAFMR\n0BR': 'studio', 
                                             'SAFMR\n1BR': '1BR',
                                            'SAFMR\n2BR': '2BR', 
                                            'SAFMR\n3BR': '3BR', 
                                            'SAFMR\n4BR': '4BR'})

In [27]:
#saving a csv file with just rental prices
miami_fmr_df.to_csv('miami_fmr.csv', index=False)

In [28]:
#now adding calculations related to housing affordability 

#this calculation is based on the 30% rule, which states that a household should not spend more than 30% of their income on housing
miami_fmr_df['studio_monthly_income_rq'] = miami_fmr_df['studio'] / 0.30
miami_fmr_df['1BR_monthly_income_rq'] = miami_fmr_df['1BR'] / 0.30
miami_fmr_df['2BR_monthly_income_rq'] = miami_fmr_df['2BR'] / 0.30
miami_fmr_df['3BR_monthly_income_rq'] = miami_fmr_df['3BR'] / 0.30
miami_fmr_df['4BR_monthly_income_rq'] = miami_fmr_df['4BR'] / 0.30

# this calculates the yearly income required for the different types of housing 
miami_fmr_df['studio_yrly_income_rq'] = miami_fmr_df['studio_monthly_income_rq'] * 12
miami_fmr_df['1BR_yrly_income_rq'] = miami_fmr_df['1BR_monthly_income_rq'] * 12
miami_fmr_df['2BR_yrly_income_rq'] = miami_fmr_df['2BR_monthly_income_rq'] * 12
miami_fmr_df['3BR_yrly_income_rq'] = miami_fmr_df['3BR_monthly_income_rq'] * 12
miami_fmr_df['4BR_yrly_income_rq'] = miami_fmr_df['4BR_monthly_income_rq'] * 12

# this calculates the hourly wage required to afford the different types of housing
miami_fmr_df['studio_hourly_wage_rq'] = miami_fmr_df['studio_yrly_income_rq'] / 2080
miami_fmr_df['1BR_hourly_wage_rq'] = miami_fmr_df['1BR_yrly_income_rq'] / 2080
miami_fmr_df['2BR_hourly_wage_rq'] = miami_fmr_df['2BR_yrly_income_rq'] / 2080
miami_fmr_df['3BR_hourly_wage_rq'] = miami_fmr_df['3BR_yrly_income_rq'] / 2080
miami_fmr_df['4BR_hourly_wage_rq'] = miami_fmr_df['4BR_yrly_income_rq'] / 2080

In [30]:
#converting all calculations to integers
calculations = ['studio_monthly_income_rq', '1BR_monthly_income_rq',
       '2BR_monthly_income_rq', '3BR_monthly_income_rq',
       '4BR_monthly_income_rq', 'studio_yrly_income_rq', '1BR_yrly_income_rq',
       '2BR_yrly_income_rq', '3BR_yrly_income_rq', '4BR_yrly_income_rq',
       'studio_hourly_wage_rq', '1BR_hourly_wage_rq', '2BR_hourly_wage_rq',
       '3BR_hourly_wage_rq', '4BR_hourly_wage_rq']

for col in calculations:
    miami_fmr_df[col] = miami_fmr_df[col].astype(int)

In [31]:
#resetting index
miami_fmr_df = miami_fmr_df.reset_index(drop=True)
miami_fmr_df

,zip_code,studio,1BR,2BR,3BR,4BR,studio_monthly_income_rq,1BR_monthly_income_rq,2BR_monthly_income_rq,3BR_monthly_income_rq,...,studio_yrly_income_rq,1BR_yrly_income_rq,2BR_yrly_income_rq,3BR_yrly_income_rq,4BR_yrly_income_rq,studio_hourly_wage_rq,1BR_hourly_wage_rq,2BR_hourly_wage_rq,3BR_hourly_wage_rq,4BR_hourly_wage_rq
0,33002,1360,1540,1920,2530,2990,4533,5133,6400,8433,...,54400,61600,76800,101200,119600,26,29,36,48,57
1,33010,1150,1310,1630,2140,2540,3833,4366,5433,7133,...,46000,52400,65200,85600,101600,22,25,31,41,48
2,33011,1360,1540,1920,2530,2990,4533,5133,6400,8433,...,54400,61600,76800,101200,119600,26,29,36,48,57
3,33012,1230,1400,1740,2290,2710,4100,4666,5800,7633,...,49200,56000,69600,91600,108400,23,26,33,44,52
4,33013,1150,1310,1630,2140,2540,3833,4366,5433,7133,...,46000,52400,65200,85600,101600,22,25,31,41,48
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,33266,1360,1540,1920,2530,2990,4533,5133,6400,8433,...,54400,61600,76800,101200,119600,26,29,36,48,57
116,33269,1360,1540,1920,2530,2990,4533,5133,6400,8433,...,54400,61600,76800,101200,119600,26,29,36,48,57
117,33280,1360,1540,1920,2530,2990,4533,5133,6400,8433,...,54400,61600,76800,101200,119600,26,29,36,48,57
118,33283,1360,1540,1920,2530,2990,4533,5133,6400,8433,...,54400,61600,76800,101200,119600,26,29,36,48,57
119,33296,1360,1540,1920,2530,2990,4533,5133,6400,8433,...,54400,61600,76800,101200,119600,26,29,36,48,57

In [33]:
#reordering columns for better understanding
miami_fmr_df = miami_fmr_df[['zip_code', 'studio', 'studio_monthly_income_rq', 'studio_yrly_income_rq', 'studio_hourly_wage_rq',
                             '1BR', '1BR_monthly_income_rq', '1BR_yrly_income_rq', '1BR_hourly_wage_rq',
                             '2BR', '2BR_monthly_income_rq', '2BR_yrly_income_rq', '2BR_hourly_wage_rq',
                             '3BR', '3BR_monthly_income_rq', '3BR_yrly_income_rq', '3BR_hourly_wage_rq',
                             '4BR', '4BR_monthly_income_rq', '4BR_yrly_income_rq', '4BR_hourly_wage_rq']]

In [35]:
#saving as its own dataframe 
miami_fmr_df.to_csv('miami_fmr_df_with_calculations.csv', index=False)